# Start from official Flink base image
FROM flink:1.17.1

# Switch to root user to install additional packages
USER root

# Install Python3 and pip
RUN apt-get update && apt-get install -y python3 python3-pip && \
    ln -s /usr/bin/python3 /usr/bin/python

# Set working directory for your flink jobs
WORKDIR /opt/flink_jobs

# Copy your Python Flink jobs into the container
COPY flink_jobs/ /opt/flink_jobs/

# Copy Kafka Connector JARs into the container
COPY libs/ /opt/flink_libs/

# Install PyFlink and Snowflake Connector for Python
RUN pip3 install apache-flink==1.17.1 snowflake-connector-python

# Set working directory again (safety)
WORKDIR /opt/flink_jobs
